-- Procedure Creation
CREATE PROCEDURE ERENLIB2.SP_GET_STOCK (
  INOUT P_SKODE  CHAR(15), 
  OUT   P_SNAME  CHAR(40), 
  OUT   P_SQTY   DECIMAL(11, 2),
  OUT   P_STAT   CHAR(10)
)
LANGUAGE RPGLE
SPECIFIC ERENLIB2.SP_GET_STOCK
EXTERNAL NAME ERENLIB2.GETSTKR
PARAMETER STYLE GENERAL;

-- Consumption (Test)
CALL ERENLIB2.SP_GET_STOCK('FERMUAR01', ?, ?, ?);

CALL ERENLIB2.SP_GET_STOCK(?, ?, ?, ?);; --will request input